import { WorkspaceFile, WorkspaceFolder } from "./types";

export const initialFolders: WorkspaceFolder[] = [
  { id: "folder-arch", name: "Architecture", count: 3 },
  { id: "folder-eng", name: "Engineering", count: 2 },
  { id: "folder-specs", name: "Design Specs", count: 1 },
];

export const initialFiles: WorkspaceFile[] = [
  {
    id: "file-untitled-1",
    name: "Untitled File",
    type: "markdown",
    location: null,
    createdAt: "1 week ago",
    createdTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    editedAt: "1 week ago",
    editedTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    commentsCount: 0,
    author: {
      name: "Sarthak Gupta",
      initials: "SG",
      color: "bg-amber-600",
    },
    isPrivate: false,
    isArchived: false,
  },
  {
    id: "file-trace-arch",
    name: "Trace System Architecture & Yjs Sync Flow",
    type: "architecture",
    location: "Architecture",
    createdAt: "3 days ago",
    createdTimestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    editedAt: "15 mins ago",
    editedTimestamp: Date.now() - 15 * 60 * 1000,
    commentsCount: 4,
    author: {
      name: "Ada Lovelace",
      initials: "AL",
      color: "bg-blue-600",
    },
    isPrivate: false,
    isArchived: false,
  },
  {
    id: "file-db-schema",
    name: "PostgreSQL Database Schema v2 (Drizzle)",
    type: "dbml",
    location: "Engineering",
    createdAt: "5 days ago",
    createdTimestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    editedAt: "2 hours ago",
    editedTimestamp: Date.now() - 2 * 60 * 60 * 1000,
    commentsCount: 2,
    author: {
      name: "Sarthak Gupta",
      initials: "SG",
      color: "bg-amber-600",
    },
    isPrivate: false,
    isArchived: false,
  },
  {
    id: "file-auth-spec",
    name: "Better Auth Session & Role Verification Specs",
    type: "markdown",
    location: "Architecture",
    createdAt: "2 weeks ago",
    createdTimestamp: Date.now() - 14 * 24 * 60 * 60 * 1000,
    editedAt: "Yesterday",
    editedTimestamp: Date.now() - 24 * 60 * 60 * 1000,
    commentsCount: 6,
    author: {
      name: "Jordan Doe",
      initials: "JD",
      color: "bg-emerald-600",
    },
    isPrivate: false,
    isArchived: false,
  },
  {
    id: "file-state-flow",
    name: "Collaborative Canvas State Machine",
    type: "flow",
    location: "Engineering",
    createdAt: "1 week ago",
    createdTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    editedAt: "3 days ago",
    editedTimestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    commentsCount: 1,
    author: {
      name: "Sarthak Gupta",
      initials: "SG",
      color: "bg-amber-600",
    },
    isPrivate: false,
    isArchived: false,
  },
  {
    id: "file-ui-tokens",
    name: "Warm Canvas Design Tokens & Hand-drawn Assets",
    type: "markdown",
    location: "Design Specs",
    createdAt: "4 days ago",
    createdTimestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    editedAt: "5 hours ago",
    editedTimestamp: Date.now() - 5 * 60 * 60 * 1000,
    commentsCount: 3,
    author: {
      name: "Ada Lovelace",
      initials: "AL",
      color: "bg-blue-600",
    },
    isPrivate: false,
    isArchived: false,
  },
];

export const teamMembers = [
  {
    name: "Sarthak Gupta",
    email: "sarthak@trace.dev",
    initials: "SG",
    role: "Owner",
    color: "bg-amber-600",
  },
  {
    name: "Ada Lovelace",
    email: "ada@trace.dev",
    initials: "AL",
    role: "Editor",
    color: "bg-blue-600",
  },
  {
    name: "Jordan Doe",
    email: "jordan@trace.dev",
    initials: "JD",
    role: "Viewer",
    color: "bg-emerald-600",
  },
];
